### ISSUE TITLE
project description

### ISSUE THREAD

**Issue by larshp** [VishnAndr/zuiddlb#2]
Hi @VishnAndr 
can you help adding a project description,

![image](https://user-images.githubusercontent.com/5888506/32990334-1d6dd12e-cd28-11e7-9ebe-a8d83be5a73f.png)

**Comment by VishnAndr** [comment]
Not sure why you can't see it. However, Readme. MD is there and other files are there as well. Checked it in incognito - all good for me

**Comment by VishnAndr** [comment]
![screenshot_20171119-235044](https://user-images.githubusercontent.com/4543139/32990858-f26a4932-cd84-11e7-8fa8-1c0c2a312481.png)

**Comment by larshp** [comment]
Sorry, I'm refering to the GitHub project description, which is stored separately from the readme, see https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github

**Comment by VishnAndr** [comment]
Thanks, @larshp. Done.

**Comment by larshp** [comment]
cool
